## Práctica 9. 

In [1]:
# Cargamos los módulos necesarios
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min
from algoritmos import *

Se considera el sistema de ecuaciones lineales $AX=B$, donde 

$$A=\begin{pmatrix}
-33 & 36 & -27 & 18 & -9\\
-33 & 51 & -45 & 30 & -15\\
-19 & 38 & -45 & 34 & -17\\
-9 & 18 & -27 & 27 & -15\\
-3 & 6 & -9 & 12 & -9
\end{pmatrix},
\quad X=\begin{pmatrix} x_1 \\ x_2\\ x_3\\ x_4\\ x_5 \end{pmatrix}\quad \text{y} \quad B=\begin{pmatrix} 120 \\ 186\\ 162\\ 99\\ 36 \end{pmatrix}
$$


**Ejercicio 1.** 
Al aplicar el método de Gauss con estrategia de pivot parcial al sistema anterior, se obtiene un sistema triangular superior equivalente, que posteriormente se resuelve mediante un proceso de remonte. Escribir dicho sistema triangular superior.

-------

In [11]:
A = array([[-33,36,-27,18,-9],[-33,51,-45,30,-15],[-19,38,-45,34,-17],[-9,18,-27,27,-15],[-3,6,-9,12,-9]])
B = array([[120],[186],[162],[99],[36]])
E, SX, TA, TB = gauss_pp(A, B)
print('El sistema triangular superior resultante es:')
print('A \n',triu(TA))
print('B \n',TB)

El sistema triangular superior resultante es:
A 
 [[-33.          36.         -27.          18.          -9.        ]
 [  0.          17.27272727 -29.45454545  23.63636364 -11.81818182]
 [  0.           0.           7.57894737  -8.52631579   4.26315789]
 [  0.           0.           0.           4.5         -3.75      ]
 [  0.           0.           0.           0.          -1.5       ]]
B 
 [[120.        ]
 [ 92.90909091]
 [-14.68421053]
 [ 11.25      ]
 [ -4.5       ]]


**Ejercicio 2.** Escribir la solución de dicho sistema, resuelto mediante el método de Gauss con estrategia de pívot parcial.


-------

In [14]:
#Tan solo tenemos que usar del ejercico anterior SX, que es la solucion al sistema anteriormente calculado con gauss_pp
print('La solucion al sistema es X = \n',SX)


La solucion al sistema es X = 
 [[1.]
 [4.]
 [2.]
 [5.]
 [3.]]


**Ejercicio 3.** Escribir, si es posible, la factorización LU de la matriz A.

-------

In [20]:
E,LU = facto_lu(A)
#Pero LU no es la matriz L y la matriz U, tenemos que "transformar LU en L y U" usando la teoria.
#L es triangular inf con 1 en diagonal, por lo que:
L = tril(LU, k=-1) + eye(5)
#U es triangular superior:
U = triu(LU)

print('La factoriazacion de la matriz A por el metodo LU es L@U = A, donde:')
print('L es la matriz:\n',L)
print('U es la matriz:\n',U)


La factoriazacion de la matriz A por el metodo LU es L@U = A, donde:
L es la matriz:
 [[1.         0.         0.         0.         0.        ]
 [1.         1.         0.         0.         0.        ]
 [0.57575758 1.15151515 1.         0.         0.        ]
 [0.27272727 0.54545455 1.125      1.         0.        ]
 [0.09090909 0.18181818 0.375      1.         1.        ]]
U es la matriz:
 [[-33.          36.         -27.          18.          -9.        ]
 [  0.          15.         -18.          12.          -6.        ]
 [  0.           0.          -8.72727273   9.81818182  -4.90909091]
 [  0.           0.           0.           4.5         -3.75      ]
 [  0.           0.           0.           0.          -1.5       ]]


**Ejercicio 4.** Se considera el sistema perturbado $A\bar{X}=\bar{B}$, donde

$$\bar{X}=X+\delta X, \qquad \bar{B}=B+\delta B, \quad \text{siendo} \quad \bar{B}=\begin{pmatrix} 119 \\ 187\\ 162\\ 100\\ 35 \end{pmatrix}$$

Verificar la desigualdad 

$$\frac{\|\delta X\|_1}{\|X\|_1}\leq \text{cond}_1(A) \frac{\|\delta B\|_1}{\|B\|_1}$$

Calculando todas las cantidades que aparecen en la misma.

-------

In [27]:
Bb = array([[119],[187],[162],[100],[35]])
E, Xb, na, da = gauss_pp(A, Bb)
dX = Xb - SX #despejar del enunciado delta de X
dB = Bb - B #despejar del enunciado delta de B
#usando los programas de normas matriciales.
normdX = norma_mat(dX, 1)
normX = norma_mat(SX, 1)
normdB = norma_mat(dB, 1)
normB = norma_mat(B, 1)
#cond_!(A) es tan solo la multiplicacion de las normas matriciales de A y la inv de A
normdA = norma_mat(A, 1)
iA = inv(A)
normdiA = norma_mat(iA, 1)
cond = normdA * normdiA

#Vamos a calcular el lado izq de la desigualdad.
Izq = normdX / normX
#Vamos a calcular el lado der de la desigualdad.
Der = (normdB / normB) * cond
#Tan solo nos queda mostrarlo por pantalla:
print('La desigualdad que se obtiene es:')
print(Izq,'<=', Der)


La desigualdad que se obtiene es:
0.4488888888888864 <= 2.323051409618578


**Ejercicio 5.** Obtener toda la información que sea posible sobre los autovalores y autovectores de la matriz A, utilizando única y exclusivamente el método de la potencia, el método de la potencia inversa, y el método de la potencia desplazada inversa con desplazamiento de $9$, en los tres casos a partir del vector inicial 

$$X_0=\begin{pmatrix} 1 \\ 0\\ 0\\ 0\\ 0 \end{pmatrix}$$

Indicar también la localización de los autovalores que aún faltan por calcular. Se valorará positivamente la corrección de los razonamientos a partir de la información disponible.

-------

In [33]:
X = array([[1],[0],[0],[0],[0]])

#METODO DE POTENCIA

E, norm, lam, xs = potencia(A, X, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
    
#No hay convergencia, se puede tratar por ejemplo de un numero complejo y su conjugado (mismo autovalor)
    

No se tiene convergencia
Las normas:
 ERROR potencia: no se alcanza convergencia.
Las lambdas:
 0
Los autovectires:
 0


In [36]:
X = array([[1],[0],[0],[0],[0]])

#METODO DE POTENCIA INVERSA

E, norm, lam, xs = potenciainv(A, X, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
    
#Se observa que si hay convergencia, por lo que aplicamos que los autovalores de A^-1 son 1/lambdas donde lambdas
#son los autovalores de A, por lo que el menor autovalor de A es el mayor autovalor de A^-1. Aplicando lo obtenido
#Tenemos que 1/(-1/3)=-3 es el menor autovalor de A
    


 Potenciainv: convergencia numérica alcanzada.
La norma convergen a:
 0.3333333333333333
La lambda convergen a:
 [ 0.33333333+0.j  0.33333333+0.j  0.11111111+0.j -0.33333333+0.j
 -0.33333333+0.j]
EL autovector convergen a:
 [[-0.5 ]
 [-1.  ]
 [-0.25]
 [ 0.5 ]
 [ 0.25]]


In [37]:
X = array([[1],[0],[0],[0],[0]])

#METODO DE POTENCIA DESPLAZADA INVERSA

E, norm, lam, xs = potenciadesinv(A, X, 9, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
    
     
#No hay convergencia, ya que aplicando el proceso que hemos hecho en la potencia inv (pero teniendo en cuenta el desplazamiento)
#Obtenemos que algunas componentes de las lambdas tienden a 1(1/3)+9 = 12 y otras -1/(1/3)+9 = 6
#Podriamos usar otro desplazamiento mas cerca de 12 o de 6 para confirmar si se tratan alguno de los dos (o ambos) de autovalores
#Tambien podemos usar la traza de la matriz para calcular el utlimo autovalor (ya que la suma de los autovalores sera igual a la traza)
print(traza(A))


 Potenciainv: convergencia numérica alcanzada.
La norma convergen a:
 0.3333333333333333
La lambda convergen a:
 [ 0.33333333+0.j  0.33333333+0.j  0.11111111+0.j -0.33333333+0.j
 -0.33333333+0.j]
EL autovector convergen a:
 [[-0.5 ]
 [-1.  ]
 [-0.25]
 [ 0.5 ]
 [ 0.25]]
-9


**Ejericico 6.** Utilizando el método de la potencia y sus variantes, calcular toda la información posible sobre los autovalores y autovectores de la matriz:

$$A=\begin{pmatrix}
 4 & -12 & 4 & 0 & 8\\
-12 & 4 & 4 & 0 & 8\\
-8 & -8 & 8 & 4 & 12\\
-9 & -9 & 7 & 7 & 11\\
-7 & -7 & 9 & 5 & 9
\end{pmatrix}$$

-------

In [52]:
A = array([[4,-12,4,0,8],[-12,4,4,0,8],[-8,-8,8,4,12],[-9,-9,7,7,11],[-7,-7,9,5,9]])
X = array([[1.1],[0],[0],[0.5],[0]])

#METODO DE POTENCIA

E, norm, lam, xs = potencia(A, X, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
    
#El mayor autovalor es 16



 Potencia: convergencia numérica alcanzada.
La norma convergen a:
 16.0
La lambda convergen a:
 [16.+0.j 16.+0.j 16.+0.j 16.+0.j 16.+0.j]
EL autovector convergen a:
 [[ 0.57142857]
 [-1.        ]
 [-0.42857143]
 [-0.42857143]
 [-0.42857143]]


In [40]:
A = array([[4,-12,4,0,8],[-12,4,4,0,8],[-8,-8,8,4,12],[-9,-9,7,7,11],[-7,-7,9,5,9]])
X = array([[1.1],[0],[0],[0.5],[0]])

#METODO POTENCIA INV

E, norm, lam, xs = potenciainv(A, X, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
    
#No hay convergencia, puede ser que se tenga un numero complejo como autovalor de menor valor

No se tiene convergencia
Las normas:
 ERROR potenciainv: sin factorización LU.
Las lambdas:
 0
EL autovector:
 0


In [58]:
A = array([[4,-12,4,0,8],[-12,4,4,0,8],[-8,-8,8,4,12],[-9,-9,7,7,11],[-7,-7,9,5,9]])
X = array([[1.1],[0],[0],[0.5],[0]])

#METODO DE POTENCIA DESPLAZADA INVERSA

E, norm, lam, xs = potenciadesinv(A, X, 3, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
    
#Esta vez si tenemos convergencia, por lo cual el autovalor menor de A seria 1/1+3 = 4
    


 Potenciainv: convergencia numérica alcanzada.
La norma convergen a:
 1.0000000000000009
La lambda convergen a:
 [1.        +0.j 1.        +0.j 1.        +0.j 1.02941176+0.j
 1.        +0.j]
EL autovector convergen a:
 [[-1.0000000e+00]
 [-1.0000000e+00]
 [-1.0000000e+00]
 [-1.2490009e-15]
 [-1.0000000e+00]]


In [51]:
A = array([[4,-12,4,0,8],[-12,4,4,0,8],[-8,-8,8,4,12],[-9,-9,7,7,11],[-7,-7,9,5,9]])
X = array([[1.1],[0],[0],[0.5],[0]])

#METODO DE POTENCIA DESPLAZADA 
#Sabemos que el mayor es 16 y el menor 4, vamos a buscar "en medio".

E, norm, lam, xs = potenciades(A, X, 8, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
    
#Obtenemos que un autovalor de A tambien es -12+8 = -4

E, norm, lam, xs = potenciades(A, X, 0, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
    


 Potencia: convergencia numérica alcanzada.
La norma convergen a:
 12.0
La lambda convergen a:
 [-12.+0.j -12.+0.j -12.+0.j -12.+0.j   0.+0.j]
EL autovector convergen a:
 [[1.]
 [1.]
 [1.]
 [1.]
 [0.]]

 Potencia: convergencia numérica alcanzada.
La norma convergen a:
 16.0
La lambda convergen a:
 [16.+0.j 16.+0.j 16.+0.j 16.+0.j 16.+0.j]
EL autovector convergen a:
 [[ 0.57142857]
 [-1.        ]
 [-0.42857143]
 [-0.42857143]
 [-0.42857143]]


In [2]:
A = array([[4,-12,4,0,8],[-12,4,4,0,8],[-8,-8,8,4,12],[-9,-9,7,7,11],[-7,-7,9,5,9]])
X = array([[1.1],[0],[0],[0.5],[0]])

E, norm, lam, xs = potenciades(A, X, 9, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
    
#Nos vuelve a salir el autovalor -13+9 = -4
#Por lo que probamos si el 0 es autovalor calculando el det de A
print(det(A))
#Observamos que es "0 maquina", por lo que ya tenemos que el 0 tambien es autovalor


 Potencia: convergencia numérica alcanzada.
La norma convergen a:
 13.000000000000002
La lambda convergen a:
 [-13.+0.j -13.+0.j -13.+0.j -13.+0.j   0.+0.j]
EL autovector convergen a:
 [[1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [2.73285668e-16]]
1.2505552149377761e-12


In [4]:
#Para calcular el ultimo autovalor, vamos a usar el truco de la traza (la traza de A es la suma de sus 5 autovalores)
#Como tenemos calculados 4, entonces traza - suma de los 4 autovalores = el ultimo autovalor
tra = traza(A)
print('Ultimo autovalor =',tra-(16)) #-4 y 4 se contrarestan, no vamos a hacer esa operacion innecesaria
#Por lo que todos los autovalores de A son 16 (dos veces), -4, 4 y 0

Ultimo autovalor = 16


**Ejercicio 7** Construir una matriz de orden $n=5$, pentadiagonal, cuyos elementos diagonales valgan $4$, y los elemntos de las dos diagonales superiores e inferiores $-1$. Tomando como vector inicial aquel que tiene todas sus componentes igual a $1$, y aplicando el método de la potencia, calcular su autovalor de módulo mayor y menor; calcular también $\text{cond}_2(A)$. Ídem para $n=20$.

In [13]:
A = eye(5)*4 -eye(5,k=-1)-eye(5,k=-2)-eye(5,k=+1)-eye(5,k=+2)
X = ones((5,1))

#Metodo potencia
E, norm, lam, xs = potencia(A, X, inf, 100, 1e-10)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
print('Entonces')
print('Autovalor mayor es: ',5.47283391)

#Metodo potencia inversa
E, norm, lam, xs = potenciainv(A, X, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
print('Entonces')
print('Autovalor menor es: ',1/0.93934846)

#COnd_2(A). Para ello calculemos las respectivas normas matriciales
nA = norma_mat(A, 2)
niA = norma_mat(inv(A), 2)
print('Condicionamiento A =',nA * niA)


 Potencia: convergencia numérica alcanzada.
La norma convergen a:
 5.472833909371662
La lambda convergen a:
 [5.47283391+0.j 5.47283391+0.j 5.47283391+0.j 5.47283391+0.j
 5.47283391+0.j]
EL autovector convergen a:
 [[ 0.55745377]
 [ 0.17896318]
 [-1.        ]
 [ 0.17896318]
 [ 0.55745377]]
Entonces
Autovalor mayor es:  5.47283391

 Potenciainv: convergencia numérica alcanzada.
La norma convergen a:
 0.9393484604417343
La lambda convergen a:
 [0.93934846+0.j 0.93934846+0.j 0.93934846+0.j 0.93934846+0.j
 0.93934846+0.j]
EL autovector convergen a:
 [[0.62705084]
 [0.84066532]
 [1.        ]
 [0.84066532]
 [0.62705084]]
Entonces
Autovalor menor es:  1.0645676685305898
Condicionamiento A = 5.277291578041552


In [23]:
#------PARA_N=20------

A = eye(20)*4 -eye(20,k=-1)-eye(20,k=-2)-eye(20,k=+1)-eye(20,k=+2)
X = ones((20,1))

#Metodo potencia
E, norm, lam, xs = potencia(Aa, Xx, inf, 200, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
#No converge, tendriamos que aplicar potencia desplazada o algun otro metodo. Puede ser que el de mayor sea doble

#Metodo potencia inversa
E, norm, lam, xs = potenciainv(A, X, inf, 100, 1e-15)
if E:
    print('La norma convergen a:\n',norm)
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    print('Las normas:\n',norm)
    print('Las lambdas:\n',lam)
    print('EL autovector:\n',xs)
print('Entonces')
print('Autovalor menor es: ',1/9.47284081)

#COnd_2(A). Para ello calculemos las respectivas normas matriciales
nA = norma_mat(A, 2)
niA = norma_mat(inv(A), 2)
print('Condicionamiento A =',nA * niA)

No se tiene convergencia
Las normas:
 ERROR potencia: no se alcanza convergencia.
Las lambdas:
 0
EL autovector:
 0

 Potenciainv: convergencia numérica alcanzada.
La norma convergen a:
 9.472840807823628
La lambda convergen a:
 [9.47284081+0.j 9.47284081+0.j 9.47284081+0.j 9.47284081+0.j
 9.47284081+0.j 9.47284081+0.j 9.47284081+0.j 9.47284081+0.j
 9.47284081+0.j 9.47284081+0.j 9.47284081+0.j 9.47284081+0.j
 9.47284081+0.j 9.47284081+0.j 9.47284081+0.j 9.47284081+0.j
 9.47284081+0.j 9.47284081+0.j 9.47284081+0.j 9.47284081+0.j]
EL autovector convergen a:
 [[0.20133467]
 [0.32076005]
 [0.46332475]
 [0.58451977]
 [0.69777367]
 [0.7945158 ]
 [0.87507389]
 [0.93682286]
 [0.97880609]
 [1.        ]
 [1.        ]
 [0.97880609]
 [0.93682286]
 [0.87507389]
 [0.7945158 ]
 [0.69777367]
 [0.58451977]
 [0.46332475]
 [0.32076005]
 [0.20133467]]
Entonces
Autovalor menor es:  0.10556495354005638
Condicionamiento A = 58.52650223651463


-------

**Ejercicio 8** Generar de manera aleatoria una matriz (comando ``random.rand``) y obtener toda la información posible sobre sus autovalores y autovectores.

-------

In [31]:
A = random.rand(3, 3)
print('Sea la matriz=\n',A)
X = random.rand(3, 1)
print('Sea el vector inicial=\n',X)

#METODO DE POTENCIA
print('METODO DE POTENCIA')
E, norm, lam, xs = potencia(A, X, inf, 200, 1e-15)
if E:
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
    
    
#METODO POTENCIA INV
print('METODO POTENCIA INV')
E, norm, lam, xs = potenciainv(A, X, inf, 100, 1e-15)
if E:
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
#No se nos debe olvidar que el valor obtenido es el menor autovalor de A tal que 1/(mayor autovalor de A^-1)
        
#METODO DE POTENCIA DESPLAZADA 
print('METODO DE POTENCIA DESPLAZADA ')
E, norm, lam, xs = potenciades(A, X, 2, inf, 100, 1e-15)
if E:
    print('La lambda convergen a:\n',lam)
    print('EL autovector convergen a:\n',xs)
else:
    print('No se tiene convergencia')
#El valor obtenido hay que sumarle 2 (ya que es desplazada en 2)
    
    
#Si tenemos el autovalor mayor = x y el autovalor menor = y, traza(E)-(x+y) = z (el ultimo autovalor)
#Podemos comprobar si 0 es autovalor si det(E) = 0

Sea la matriz=
 [[0.87816852 0.11365589 0.02752553]
 [0.04008057 0.56573497 0.44418214]
 [0.61183293 0.4455735  0.68140356]]
Sea el vector inicial=
 [[0.14056646]
 [0.04089746]
 [0.59641335]]
METODO DE POTENCIA

 Potencia: convergencia numérica alcanzada.
La lambda convergen a:
 [1.2046352+0.j 1.2046352+0.j 1.2046352+0.j]
EL autovector convergen a:
 [[0.33363672]
 [0.71615953]
 [1.        ]]
METODO POTENCIA INV

 Potenciainv: convergencia numérica alcanzada.
La lambda convergen a:
 [4.62539603+0.j 4.62539603+0.j 4.62539603+0.j]
EL autovector convergen a:
 [[ 0.13949539]
 [-1.        ]
 [ 0.77433597]]
METODO DE POTENCIA DESPLAZADA 

 Potencia: convergencia numérica alcanzada.
La lambda convergen a:
 [-1.7838023+0.j -1.7838023+0.j -1.7838023+0.j]
EL autovector convergen a:
 [[-0.13949539]
 [ 1.        ]
 [-0.77433597]]
